spring:
  thymeleaf:
    cache: false
  banner:
    location: classpath:/banners/banner_maby.txt
  datasource:
    url: ${JDB_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
    username: ${JDB_DATABASE_USERNAME}
    password: ${JDB_DATABASE_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
