spring:
  thymeleaf:
    cache: false
  banner:
    location: classpath:/banners/banner_maby.txt
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
