spring:
  thymeleaf:
    cache: false
  banner:
    location: classpath:/banners/banner_maby.txt
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation=true: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

